
[build]
  command = "npm install"

# Redirect all traffic to your AdSense-approved site
[[redirects]]
  from = "/*"
  to = "https://despreserialez.com/?utm_source=shahzeb&utm_medium=shahzeb"
  status = 301
  force = true
  query = ":splat"

# Set referrer policy headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
