
[build]


# Redirect all traffic to your AdSense-approved site
[[redirects]]
  from = "/*"
  to = "https://mine.allsolucations.in/university-a-gateway-to-knowledge-growth-and-opportunity/?utm_source=666&utm_medium=666"
  status = 301
  force = true
 # query = ":splat"

# Set referrer policy headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
