
[build]
  command = "npm install"

# Redirect all traffic to your AdSense-approved site
[[redirects]]
  from = "/v/*"
  to = "video.html"
  status = 301
  force = true
  query = ":splat"
[[redirects]]
  from = "index.html"
  to = "video.html"
  status = 301
  force = true
  query = ":splat"

# Set referrer policy headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
