[build]
  command = "npm install"

[[redirects]]
  from = "/v/*"
  to = "/video.html"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/video.html"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
