[build]
  command = "npm install"

[[redirects]]
  from = "/*"
  to = "https://global1.bollywoodbiofacts.com/top-20-best-hospitals-in-bangalore-2025/?utm_source=SRm&utm_medium=s"
  status = 301
  force = true


[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
