
[build]
  command = "npm install"

# Redirect all traffic to your AdSense-approved site
[[redirects]]
  from = "/*"
  to = "https://www.revenuecpmgate.com/qpw1dm7gt?key=b06b34a800fa3c4e9065db751e48a6e5"
  status = 301
  force = true
  query = ":splat"

# Set referrer policy headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
