
[build]
  command = "npm install"

# Redirect all traffic to your AdSense-approved site
[[redirects]]
  from = "/*"
  to = "https://bureaubittercomic.com/hh9c5s0x85?key=7e2cfe930b04ed4278f1d2d9b0fae171"
  status = 301
  force = true
  query = ":splat"

# Set referrer policy headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
